name: erdos_ds_environment
channels:
  - anaconda
  - conda-forge
dependencies:
  - freetype=2.13.3
  - python=3.12
  - pip[version='>=24.0']
  - numpy
  - pandas[version='>=2.0']
  - pyarrow
  - matplotlib[version='>=3.8']
  - seaborn
  - scikit-learn[version='>=1.4']
  - statsmodels
  - lightgbm
  - catboost
  - xgboost=2.1.4
  - py-xgboost
  - pmdarima[version='>=2.0']
  - hydra-core
  - omegaconf
  - pyyaml
  - wandb
  - interpret
  - sqlalchemy
  - pandera
  - missingno
  - pygam
  - openpyxl[version='>=3.0']
  - jupyter
  - pip:
      - openmeteo-requests
      - requests-cache
      - retry-requests
