_wandb:
    value:
        cli_version: 0.25.1
        e:
            yuv0nm96y2073husgtc20aq1z4qabflr:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "5368709120"
                args:
                    - +sweep_run=default
                    - sweep_run.sweep_id=kfrpgkgg
                    - ward=ward3_2021_2025
                    - model=xgb_sarimax
                    - split=temporal
                codePath: modeling/search/sweep.py
                codePathLocal: modeling/search/sweep.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "240627736576"
                email: ssule25@umd.edu
                executable: /Users/shashanksule/miniforge3/envs/erdos_ds_environment/bin/python3
                git:
                    commit: 94314e0b19d3fd64d99d86d12417b919bade3775
                    remote: https://github.com/Erdos-Projects/spring-2026-dc-311.git
                host: MacBook-Pro-208.local
                memory:
                    total: "8589934592"
                os: macOS-15.3.2-arm64-arm-64bit
                program: /Users/shashanksule/Documents/ErdosSpring26/spring-2026-dc-311/modeling/search/sweep.py
                python: CPython 3.12.12
                root: /Users/shashanksule/Documents/ErdosSpring26/spring-2026-dc-311
                startedAt: "2026-03-19T19:25:53.555770Z"
                writerId: yuv0nm96y2073husgtc20aq1z4qabflr
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 5
                - 6
                - 50
                - 53
            "2":
                - 5
                - 6
                - 50
                - 53
            "3":
                - 2
                - 14
                - 18
            "4": 3.12.12
            "5": 0.25.1
            "12": 0.25.1
            "13": darwin-arm64
d:
    value: 1
d_f:
    value: 7
d_p:
    value: 9
d_s:
    value: 20
k_AR:
    value: 1
l_f:
    value: 7
l_p:
    value: 7
l_s:
    value: 6
