_wandb:
    value:
        cli_version: 0.25.1
        e:
            5pwhrg0i5gwy7fcfqckmizrehlormskb:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "2147483648"
                args:
                    - ward=ward3_2021_2025
                    - model=xgb_sarimax
                    - split=temporal
                codePath: modeling/train.py
                codePathLocal: modeling/train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "236947054592"
                email: ssule25@umd.edu
                executable: /Users/shashanksule/miniforge3/envs/erdos_ds_environment/bin/python3
                git:
                    commit: 94314e0b19d3fd64d99d86d12417b919bade3775
                    remote: https://github.com/Erdos-Projects/spring-2026-dc-311.git
                host: MacBook-Pro-208.local
                memory:
                    total: "8589934592"
                os: macOS-15.3.2-arm64-arm-64bit
                program: /Users/shashanksule/Documents/ErdosSpring26/spring-2026-dc-311/modeling/train.py
                python: CPython 3.12.12
                root: /Users/shashanksule/Documents/ErdosSpring26/spring-2026-dc-311
                startedAt: "2026-03-19T18:01:08.295670Z"
                writerId: 5pwhrg0i5gwy7fcfqckmizrehlormskb
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 5
                - 6
                - 50
                - 53
            "2":
                - 5
                - 6
                - 50
                - 53
            "3":
                - 13
                - 14
                - 15
                - 16
            "4": 3.12.12
            "5": 0.25.1
            "12": 0.25.1
            "13": darwin-arm64
debug:
    value:
        dry_run: false
        inspect: null
        verbose: false
features:
    value:
        d: 5
        d_f: 14
        d_p: 14
        d_s: 14
        k_AR: 0
        l_f: 5
        l_p: 5
        l_s: 5
load_model:
    value: null
model:
    value:
        _target_: modeling.models.xgb_sarimax.xgb_sarimax
        auto_order: false
        learning_rate: 0.05
        max_depth: 6
        n_estimators: 300
        name: xgb_sarimax
        objective: count:poisson
        order:
            - 3
            - 0
            - 2
        seasonal_order:
            - 1
            - 1
            - 1
            - 7
root:
    value: .
split:
    value:
        method: temporal
        test_frac: 0.15
        val_frac: 0.15
wandb:
    value:
        enabled: true
        entity: ssule25-university-of-maryland
        project: DC-311-Pothole-Prediction
ward:
    value:
        name: ward3
        raw_311:
            - ./data/311_data/ward3_potholes_20210101_20251231.parquet
        ward_label: Ward 3
        weather_cache: ./data/weather_cache/weather_ward3_20200601_20251231.parquet
