_wandb:
    value:
        cli_version: 0.25.1
        e:
            546pszz824lau91rx53bvb849crj2tdp:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "9663676416"
                args:
                    - --config-name
                    - first_try
                codePath: modeling/train.py
                codePathLocal: modeling/train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "241897840640"
                email: ssule25@umd.edu
                executable: /Users/shashanksule/miniforge3/envs/erdos_ds_environment/bin/python3
                git:
                    commit: c9b03d0362ff38d439f57bb3ec0431c4dc705c0e
                    remote: https://github.com/Erdos-Projects/spring-2026-dc-311.git
                host: MacBook-Pro-208.local
                memory:
                    total: "8589934592"
                os: macOS-15.3.2-arm64-arm-64bit
                program: /Users/shashanksule/Documents/ErdosSpring26/spring-2026-dc-311/modeling/train.py
                python: CPython 3.12.12
                root: /Users/shashanksule/Documents/ErdosSpring26/spring-2026-dc-311
                startedAt: "2026-03-18T20:25:04.259254Z"
                writerId: 546pszz824lau91rx53bvb849crj2tdp
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 5
                - 50
                - 53
            "2":
                - 5
                - 50
                - 53
            "3":
                - 2
                - 13
                - 14
                - 15
                - 16
                - 61
            "4": 3.12.12
            "5": 0.25.1
            "12": 0.25.1
            "13": darwin-arm64
debug:
    value:
        dry_run: false
        inspect: null
        verbose: false
features:
    value:
        d: 5
        d_f: 14
        d_p: 14
        d_s: 14
        k_AR: 0
        l_f: 5
        l_p: 5
        l_s: 5
load_model:
    value: null
model:
    value:
        _target_: modeling.models.glm.NegBinGLM
        alpha: 1
        name: negbin_glm
split:
    value:
        random_state: 42
        test_frac: 0.15
        train_frac: 0.7
        val_frac: 0.15
wandb:
    value:
        enabled: true
        entity: ssule25-university-of-maryland
        project: DC-311-Pothole-Prediction
ward:
    value:
        name: ward3
        raw_311:
            - data/311_data/ward3_potholes_2023.parquet
        ward_label: Ward 3
        weather_cache: data/weather_cache/weather_ward3_20221201_20231231.parquet
