study_name: pothole_bayes
n_trials: 50
direction: minimize
sampler: TPESampler
top_k_warmstart: 20
search_space:
  d:    {low: 1,  high: 10}
  d_p:  {low: 7,  high: 21}
  l_p:  {low: 1,  high: 10}
  d_s:  {low: 7,  high: 21}
  l_s:  {low: 1,  high: 10}
  d_f:  {low: 7,  high: 21}
  l_f:  {low: 1,  high: 10}
  k_AR: {low: 1,  high: 10}
